name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: env
      run: |
        sudo apt-get install tmate
        ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
    - name: tmate
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string
    - name: sleep
      run: |
        while [ -S /tmp/tmate.sock ]; do
          sleep 1
        done
        
